version: "2"

services:
    bikes:
        build: ./
        environment:
            - MONGO_DB_CONNECTION_STRING=<insert connection string here>
            - MONGO_DB_COLLECTION=bikes
        ports:
            - "8080:80"