# Default values for contoso.bikerental.bikes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: stevenryregistry-microsoft.azurecr.io
  tag: latest
  pullPolicy: IfNotPresent
  repoCredsSecretName: myregistrykey
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  redisPassword: stevenry_pass
  persistence:
    enabled: false